version: '3.8'
services:
  gitlab-server:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab-server
    ports:
      - '8088:80'
    environment:
      GITLAB_ROOT_EMAIL: "vikiscripts@github.io"
      GITLAB_ROOT_PASSWORD: "Abcd@0123456789"